version: '3.8'

services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - 5000:5000
      - 9229:9229
    env_file: .env.development
    networks:
      - aibees
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:debug
    restart: unless-stopped
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 5000:5000
      - 9229:9229
    env_file: .env.production
    networks:
      - aibees
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - aibees
    environment:
      - POSTGRES_DB=aibees_ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=crudjs
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  aibees:

volumes:
  pgdata:
